#ifndef __StarFishDOM__
#define __StarFishDOM__

#include "dom/Node.h"
#include "dom/Document.h"
#include "dom/DocumentType.h"
#include "dom/HTMLDocument.h"
#include "dom/DocumentType.h"
#include "dom/CharacterData.h"
#include "dom/Text.h"
#include "dom/Comment.h"
#include "dom/HTMLDocument.h"
#include "dom/Element.h"
#include "dom/HTMLElement.h"
#include "dom/HTMLHtmlElement.h"
#include "dom/HTMLHeadElement.h"
#include "dom/HTMLScriptElement.h"
#include "dom/HTMLStyleElement.h"
#include "dom/HTMLBodyElement.h"
#include "dom/HTMLDivElement.h"
#include "dom/HTMLImageElement.h"
#include "dom/HTMLBRElement.h"
#include "dom/HTMLCollection.h"
#include "dom/HTMLUnknownElement.h"
#include "dom/DOMTokenList.h"
#include "dom/DOMSettableTokenList.h"
#include "dom/NamedNodeMap.h"
#include "dom/Attr.h"

#endif
