test/reftest/web-platform-tests/XMLHttpRequest/abort-after-receive.htm
test/reftest/web-platform-tests/XMLHttpRequest/abort-during-unsent.htm
test/reftest/web-platform-tests/XMLHttpRequest/abort-event-abort.htm
test/reftest/web-platform-tests/XMLHttpRequest/abort-event-listeners.htm
test/reftest/web-platform-tests/XMLHttpRequest/abort-event-loadend.htm
test/reftest/web-platform-tests/XMLHttpRequest/event-abort.htm
test/reftest/web-platform-tests/XMLHttpRequest/event-error.html
test/reftest/web-platform-tests/XMLHttpRequest/event-loadend.htm
test/reftest/web-platform-tests/XMLHttpRequest/event-load.htm
test/reftest/web-platform-tests/XMLHttpRequest/event-loadstart.htm
test/reftest/web-platform-tests/XMLHttpRequest/event-progress.htm
test/reftest/web-platform-tests/XMLHttpRequest/event-readystatechange-loaded.htm
test/reftest/web-platform-tests/XMLHttpRequest/event-readystate-sync-open.htm
test/reftest/web-platform-tests/XMLHttpRequest/open-after-abort.htm
test/reftest/web-platform-tests/XMLHttpRequest/open-during-abort.htm
test/reftest/web-platform-tests/XMLHttpRequest/open-user-password-non-same-origin.htm
test/reftest/web-platform-tests/XMLHttpRequest/responseText-status.html
test/reftest/web-platform-tests/XMLHttpRequest/timeout-sync.htm
test/reftest/web-platform-tests/XMLHttpRequest/xmlhttprequest-basic.htm
