#!/bin/sh
RED='\033[0;31m'
RESET='\033[0m'
echo "checking... make tidy"
make tidy
if cat error_report | grep 'ERROR'; then
 echo "$RED[FAIL] make tidy error$RESET"
 exit 1
fi

echo "checking... make internal_test"
make internal_test > prepush_test_result
if cat prepush_test_result |grep 'FAIL'; then
 echo "$RED[FAIL] make internal_test$RESET"
 exit 1
fi

echo "checking... make regression_test_blink_fast_dom"
make regression_test_blink_fast_dom > prepush_test_result
if cat prepush_test_result |grep 'FAIL'; then
 echo "$RED[FAIL] make regression_test_blink_fast_dom$RESET"
 exit 1
fi

echo "checking... make regression_test_blink_fast_html"
make regression_test_blink_fast_html > prepush_test_result
if cat prepush_test_result |grep 'FAIL'; then
 echo "$RED[FAIL] make regression_test_blink_fast_html$RESET"
 exit 1
fi

echo "checking... make regression_test_blink_fast_css"
make regression_test_blink_fast_css > prepush_test_result
if cat prepush_test_result |grep 'FAIL'; then
 echo "$RED[FAIL] make regression_test_blink_fast_css$RESET"
 exit 1
fi

echo "checking... make regression_test_blink_fast_etc"
make regression_test_blink_fast_etc > prepush_test_result
if cat prepush_test_result |grep 'FAIL'; then
 echo "$RED[FAIL] make regression_test_blink_fast_etc$RESET"
 exit 1
fi



echo "checking... make regression_test_webkit_fast_html"
make regression_test_webkit_fast_html > prepush_test_result
if cat prepush_test_result |grep 'FAIL'; then
 echo "$RED[FAIL] make regression_test_webkit_fast_html$RESET"
 exit 1
fi

echo "checking... make regression_test_webkit_fast_css"
make regression_test_webkit_fast_css > prepush_test_result
if cat prepush_test_result |grep 'FAIL'; then
 echo "$RED[FAIL] make regression_test_webkit_fast_css$RESET"
 exit 1
fi

echo "checking... make regression_test_webkit_fast_etc"
make regression_test_webkit_fast_etc > prepush_test_result
if cat prepush_test_result |grep 'FAIL'; then
 echo "$RED[FAIL] make regression_test_webkit_fast_etc$RESET"
 exit 1
fi

echo "checking... make regression_test_webkit_fast_dom"
make regression_test_webkit_fast_dom > prepush_test_result
if cat prepush_test_result |grep 'FAIL'; then
 echo "$RED[FAIL] make regression_test_webkit_fast_dom$RESET"
 exit 1
fi

echo "checking... make regression_test_wpt_dom"
make regression_test_wpt_dom > prepush_test_result
if cat prepush_test_result |grep 'FAIL'; then
 echo "$RED[FAIL] make regression_test_wpt_dom$RESET"
 exit 1
fi

echo "checking... make regression_test_wpt_html"
make regression_test_wpt_html > prepush_test_result
if cat prepush_test_result |grep 'FAIL'; then
 echo "$RED[FAIL] make regression_test_wpt_html$RESET"
 exit 1
fi

echo "checking... make regression_test_wpt_dom_events"
make regression_test_wpt_dom_events > prepush_test_result
if cat prepush_test_result |grep 'FAIL'; then
 echo "$RED[FAIL] make regression_test_wpt_dom_events$RESET"
 exit 1
fi

echo "checking... make regression_test_wpt_progress_events"
make regression_test_wpt_progress_events > prepush_test_result
if cat prepush_test_result |grep 'FAIL'; then
 echo "$RED[FAIL] make regression_test_wpt_progress_events$RESET"
 exit 1
fi

echo "checking... make regression_test_wpt_page_visibility"
make regression_test_wpt_page_visibility > prepush_test_result
if cat prepush_test_result |grep 'FAIL'; then
 echo "$RED[FAIL] make regression_test_wpt_page_visibility$RESET"
 exit 1
fi

echo "checking... make regression_test_wpt_xhr"
make regression_test_wpt_xhr > prepush_test_result
if cat prepush_test_result |grep 'FAIL'; then
 echo "$RED[FAIL] make regression_test_wpt_xhr$RESET"
 exit 1
fi

echo "checking... make regression_test_dom_conformance_test"
make regression_test_dom_conformance_test > prepush_test_result
if cat prepush_test_result |grep 'FAIL'; then
 echo "$RED[FAIL] make regression_test_dom_conformance_test$RESET"
 exit 1
fi

echo "checking... make regression_test_webkit_dom_conformance_test"
make regression_test_webkit_dom_conformance_test > prepush_test_result
if cat prepush_test_result |grep 'FAIL'; then
 echo "$RED[FAIL] make regression_test_webkit_dom_conformance_test$RESET"
 exit 1
fi

echo "checking... make regression_test_blink_dom_conformance_test"
make regression_test_blink_dom_conformance_test > prepush_test_result
if cat prepush_test_result |grep 'FAIL'; then
 echo "$RED[FAIL] make regression_test_blink_dom_conformance_test$RESET"
 exit 1
fi

echo "checking... make regression_test_gecko_dom_conformance_test"
make regression_test_gecko_dom_conformance_test > prepush_test_result
if cat prepush_test_result |grep 'FAIL'; then
 echo "$RED[FAIL] make regression_test_gecko_dom_conformance_test$RESET"
 exit 1
fi

#echo "checking... make regression_test_bidi"
#make regression_test_bidi > prepush_test_result
#if cat prepush_test_result |grep 'FAIL'; then
# echo "$RED[FAIL] make regression_test_wpt_bidi$RESET"
# exit 1
#fi

echo "checking... make pixel_test_css_all"
make pixel_test_css_all > prepush_test_result 2>&1
if cat prepush_test_result |grep 'Error 1'; then
 echo "$RED[FAIL] make pixel_test_css_all$RESET"
 exit 1
fi

echo "checking... make font_dependent_test_css"
make font_dependent_test_css > prepush_test_result 2>&1
if cat prepush_test_result |grep 'FAIL'; then
 echo "$RED[FAIL] make font_dependent_test_css$RESET"
 exit 1
fi

rm prepush_test_result
