test/reftest/web-platform-tests/DOMEvents_converted/ClickFakeEvent.nondocument.html
test/reftest/web-platform-tests/DOMEvents_converted/constructors.html
test/reftest/web-platform-tests/DOMEvents_converted/event-phases-order.html
test/reftest/web-platform-tests/DOMEvents_converted/init-event-while-dispatching.html
test/reftest/web-platform-tests/DOMEvents_converted/tests/approved/DOM.event.flow.html
test/reftest/web-platform-tests/DOMEvents_converted/tests/approved/EventListener.eventHandler.html
test/reftest/web-platform-tests/DOMEvents_converted/tests/approved/EventObject.after.dispatchEvent.html
test/reftest/web-platform-tests/DOMEvents_converted/tests/approved/EventObject.multiple.dispatchEvent.html
test/reftest/web-platform-tests/DOMEvents_converted/tests/approved/ProcessingInstruction.DOMCharacterDataModified.html
test/reftest/web-platform-tests/DOMEvents_converted/tests/approved/dispatchEvent.click.checkbox.html
test/reftest/web-platform-tests/DOMEvents_converted/tests/approved/domnodeinserted.html
test/reftest/web-platform-tests/DOMEvents_converted/tests/approved/stopImmediatePropagation.effect.html
test/reftest/web-platform-tests/DOMEvents_converted/tests/approved/stopPropagation.deferred.effect.html
test/reftest/web-platform-tests/DOMEvents_converted/tests/submissions/Microsoft/converted/DOM.event.flow.html
test/reftest/web-platform-tests/DOMEvents_converted/tests/submissions/Microsoft/converted/EventListener.dispatch.new.event.html
test/reftest/web-platform-tests/DOMEvents_converted/tests/submissions/Microsoft/converted/EventListener.eventHandler.html
test/reftest/web-platform-tests/DOMEvents_converted/tests/submissions/Microsoft/converted/EventObject.after.dispatchEvent.html
test/reftest/web-platform-tests/DOMEvents_converted/tests/submissions/Microsoft/converted/EventObject.multiple.dispatchEvent.html
test/reftest/web-platform-tests/DOMEvents_converted/tests/submissions/Microsoft/converted/ProcessingInstruction.DOMCharacterDataModified.html
test/reftest/web-platform-tests/DOMEvents_converted/tests/submissions/Microsoft/converted/dispatchEvent.click.checkbox.html
test/reftest/web-platform-tests/DOMEvents_converted/tests/submissions/Microsoft/converted/domnodeinserted.html
test/reftest/web-platform-tests/DOMEvents_converted/tests/submissions/Microsoft/converted/stopImmediatePropagation.effect.html
test/reftest/web-platform-tests/DOMEvents_converted/tests/submissions/Microsoft/converted/stopPropagation.deferred.effect.html
test/reftest/web-platform-tests/DOMEvents_converted/throwing-in-listener-and-window-error-event.html
test/reftest/web-platform-tests/DOMEvents_converted/throwing-in-listener-when-all-have-not-run-yet.html
