test/reftest/web-platform-tests/html_converted/browsers/the-window-object/window-aliases.html
test/reftest/web-platform-tests/html_converted/browsers/the-window-object/window-indexed-properties-strict.html
test/reftest/web-platform-tests/html_converted/browsers/the-window-object/window-indexed-properties.html
test/reftest/web-platform-tests/html_converted/dom/documents/dom-tree-accessors/document.getElementsByClassName-same.html
test/reftest/web-platform-tests/html_converted/dom/documents/dom-tree-accessors/document.head-01.html
test/reftest/web-platform-tests/html_converted/dom/elements/elements-in-the-dom/unknown-element.html
test/reftest/web-platform-tests/html_converted/dom/elements/global-attributes/classlist-nonstring.html
test/reftest/web-platform-tests/html_converted/dom/elements/global-attributes/id-attribute.html
test/reftest/web-platform-tests/html_converted/editing/activation/click.html
test/reftest/web-platform-tests/html_converted/semantics/grouping-content/the-div-element/grouping-div.html
test/reftest/web-platform-tests/html_converted/semantics/grouping-content/the-p-element/grouping-p.html
test/reftest/web-platform-tests/html_converted/semantics/scripting-1/the-script-element/script-onload-string.html
test/reftest/web-platform-tests/html_converted/webappapis/animation-frames/callback-invoked.html
test/reftest/web-platform-tests/html_converted/webappapis/animation-frames/callback-multicalls.html
test/reftest/web-platform-tests/html_converted/webappapis/animation-frames/cancel-invoked.html
test/reftest/web-platform-tests/html_converted/webappapis/animation-frames/same-dispatch-time.html
test/reftest/web-platform-tests/html_converted/webappapis/scripting/processing-model-2/addEventListener.html
test/reftest/web-platform-tests/html_converted/dom/documents/dom-tree-accessors/document.body-setter-01.html
test/reftest/web-platform-tests/html_converted/dom/documents/dom-tree-accessors/document.head-02.html
test/reftest/web-platform-tests/html_converted/dom/documents/dom-tree-accessors/Document.getElementsByClassName-null-undef.html
test/reftest/web-platform-tests/html_converted/dom/documents/dom-tree-accessors/Element.getElementsByClassName-null-undef.html
test/reftest/web-platform-tests/html_converted/webappapis/scripting/events/event-handler-javascript.html
test/reftest/web-platform-tests/html_converted/webappapis/scripting/events/body-onload.html
test/reftest/web-platform-tests/html_converted/dom/documents/resource-metadata-management/document-compatmode-01.html
test/reftest/web-platform-tests/html_converted/dom/documents/resource-metadata-management/document-compatmode-02.html
test/reftest/web-platform-tests/html_converted/infrastructure/conformance-requirements/extensibility/foreign.html
test/reftest/web-platform-tests/html_converted/browsers/the-window-object/window-properties.html
test/reftest/web-platform-tests/html_converted/browsers/the-window-object/window-prototype-chain.html
test/reftest/web-platform-tests/html_converted/semantics/text-level-semantics/the-bdi-element/bdi-neutral-to-another-bdi-1-ref.html

